SELECT * FROM addydb1.mytable;
-- What is the total revenue generated by male vs female customer?
SELECT gender, SUM(`purchase_amount_(usd)`) AS revenue 
FROM addydb1.mytable 
GROUP BY gender;

-- Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, `purchase_amount_(usd)`
FROM addydb1.mytable
WHERE discount_applied = 'Yes' 
  AND `purchase_amount_(usd)` >= (SELECT AVG(`purchase_amount_(usd)`) FROM addydb1.mytable);
  
-- Which are the top 5 products with the highest average review rating?
Select item_purchased, Round(avg(review_rating),2) as "Average Product Rating"
from addydb1.mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, Round(avg(`purchase_amount_(usd)`), 2)
FROM addydb1.mytable
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(`purchase_amount_(usd)`),2) as avg_spend,
round(sum(`purchase_amount_(usd)`),2) as total_revenue
from addydb1.mytable 
group by subscription_status 
order by total_revenue, avg_spend desc;

-- Which 5 products have the highest percentage of purchasese with discounts applied?
Select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from addydb1.mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into new, returning, andd loyal based on their total 
-- number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from addydb1.mytable
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

-- What are the top 3 most purchased products within each category?
with item_count as (
  select category, item_purchased,
         count(customer_id) as total_orders,
         Row_number() over(partition by category order by count(customer_id) desc) as item_rank
  from addydb1.mytable   
  group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count;

--    Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
count(customer_id) as repeat_buyers
from addydb1.mytable
where previous_purchases > 5
group by subscription_status  

-- What is the revenue contribution of each age group?
Select age_group,
Sum(`purchase_amount_(usd)`) as total_revenue
from addydb1.mytable
group by age_group
order by total_revenue desc;

